#
# Playbook to create local docker machine using the generic driver.
#
# $ ansible-playbook create-docker-machine.yml -e docker_machine_options=''
#
---
- hosts: all
  gather_facts: false

  vars:
    docker_machine_options: ""

  tasks:
    - name: Check docker machine existence
      become: false
      local_action:
        shell docker-machine config {{ inventory_hostname }}
      register: dm_present
      changed_when: "'does not exist' in dm_present.stderr or 'Error' in dm_present.stderr"
      failed_when: false
      ignore_errors: yes

    - name: Create generic docker machine
      become: false
      local_action:
        shell docker-machine create -d generic
          --generic-ssh-user {{ ansible_user }}
          --generic-ssh-key  {{ ansible_private_key_file }}
          --generic-ip-address {{ hostvars[inventory_hostname]['ansible_host'] }}
          {{ docker_machine_options }}
            {{ inventory_hostname }}
      when: dm_present|changed

    - name: Print docker machine creation command
      debug:
        msg: |
          docker-machine create -d generic
            --generic-ssh-user {{ ansible_user }}
            --generic-ssh-key  {{ ansible_private_key_file }}
            --generic-ip-address {{ hostvars[inventory_hostname]['ansible_host'] }}
            {{ docker_machine_options }}
              {{ inventory_hostname }}
      when: dm_present|changed
      tags: debug
